using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.EventSystems;

public class ClosePlanetarySkillTree : MonoBehaviour, IPointerEnterHandler, IPointerExitHandler  {

	// Tracks if mouse is hovering over panel
	public Transform planetsParent;
	private bool mouseHover;
	private GameController gc; // Access Game Controller script

	// Following code is generated by right clicking IPointerEnter/ExitHandler, and selecting "Refactor"
	public void OnPointerEnter (PointerEventData eventData)
	{
		mouseHover = true;
	}
	public void OnPointerExit (PointerEventData eventData)
	{
		mouseHover = false;
	}

	void Start()
	{
		gc = GameObject.Find("Game Manager").GetComponent<GameController>();
	}

	void Update () {
		// When player clicks outside the panel
		if (Input.GetMouseButtonUp (0) && mouseHover) {

			// Set state backwards
			if (gc.GAME_STATE == Constants.TURN_1_PLANET_SLOT) {
				gc.GAME_STATE = Constants.TURN_1_SKILL_TREE;
			}

			// Deactivate the panel
			this.transform.parent.gameObject.SetActive (false);
		}
	}
}
