using UnityEngine;
using System.Collections;
// Track events through event systems
using UnityEngine.EventSystems;

// Implement pointer interfaces programatically, instead of Scene event triggers
public class DraggableUI : MonoBehaviour, IBeginDragHandler, IDragHandler {

	private float offsetX;
	private float offsetY;

	// Following code is generated by right clicking IBeginDragHandler/IDragHandler and selecting "Refactor"
	public void OnBeginDrag (PointerEventData eventData)
	{
		offsetX = transform.position.x - Input.mousePosition.x;
		offsetY = transform.position.y - Input.mousePosition.y;
	}
	public void OnDrag (PointerEventData eventData)
	{
		transform.position = new Vector3 (offsetX + Input.mousePosition.x, offsetY + Input.mousePosition.y);
	}
}﻿