using System.Collections;
using System.Collections.Generic;
using UnityEngine;
// Track events through event systems
using UnityEngine.EventSystems;

// Implement pointer interfaces programatically, instead of Scene event triggers
public class PlanetarySkillTreeButton : MonoBehaviour, IPointerEnterHandler, IPointerExitHandler {

	public GameObject macroSkillTree; // Reference to macro skill tree
	private bool mouseHover; // Tracks if mouse is hovering over panel

	// Following code is generated by right clicking IPointerEnter/ExitHandler, and selecting "Refactor"
	public void OnPointerEnter (PointerEventData eventData) {
		mouseHover = true;
	}
	public void OnPointerExit (PointerEventData eventData) {
		mouseHover = false;
	}

	void Update () {
		// When player clicks on the icon
		if (Input.GetMouseButtonUp (0) && mouseHover) {
			// Toggle the panel
			macroSkillTree.SetActive (!macroSkillTree.activeSelf);
		}
	}
}
