using System.Collections;
using System.Collections.Generic;
using UnityEngine;
// Track events through event systems
using UnityEngine.EventSystems;

// Implement pointer interfaces programatically, instead of Scene event triggers
public class CloseOnBlur : MonoBehaviour, IPointerEnterHandler, IPointerExitHandler {

	// Tracks if mouse is hovering over panel
	private bool mouseHover;

	// Following code is generated by right clicking IPointerEnter/ExitHandler, and selecting "Refactor"
	public void OnPointerEnter (PointerEventData eventData)
	{
		mouseHover = true;
	}
	public void OnPointerExit (PointerEventData eventData)
	{
		mouseHover = false;
	}

	void Update () {
		// When player clicks outside the panel
		if (Input.GetMouseButtonUp (0) && !mouseHover) {
			// Deactivate the panel
			gameObject.SetActive (false);
		}
	}
}
